### ISSUE TITLE
kafka with scala 2.11

### ISSUE THREAD

**Issue by vsimko** [biggis-project/biggis-infrastructure#15]
In `biggis-infrastructure/biggis-docker/biggis-pipeline/biggis-kafka/Dockerfile`, you mentioned that Scala 2.10 is recommended by the Kafka project.

However, I can see on the [kafka's download](http://kafka.apache.org/downloads.html) website that since release 0.9.0.0, the recommended Scala version is actually 2.11 (which I'm also using for development).

@wipatrick Whould it be possible (preferably today) to update Kafka to the latest release (0.10.0.1) with Scala 2.11 ?

I'm getting warning messages:

```
WARN  org.apache.kafka.clients.NetworkClient - Error while fetching metadata with correlation id 0 : {de.biggis.flink.messages.TileDiscoveredMsg=LEADER_NOT_AVAILABLE}
```

**Comment by wipatrick** [comment]
As of now, Flink 1.1 doesn't seem to support Kafka 0.10.01.

see: [here](https://ci.apache.org/projects/flink/flink-docs-release-1.1/apis/streaming/connectors/kafka.html) for the versions

**Comment by vsimko** [comment]
Ok, what about kafka 0.9 + scala 2.11 ?

**Comment by wipatrick** [comment]
This issue is most likely related to a Kafka/Zookeeper issue when specifying the wrong IP for the `advertised.host.name` in the Kafka configuration which is set by the environment variable in the `docker-compose.yml`:

``` yaml
 kafka:
    image: biggis/kafka:0.9.0.0
    restart: always
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      USER_ID: ${USER_ID}
      USER_NAME: kafka
```

You need to set the `KAFKA_ADVERTISED_HOST_NAME` to the IP of your Docker Host. Please try and let me know.
